site_name: Project BLiP Docs
site_description: "Documentation for Project BLiP services"
site_author: "Sai Vipul Mohan"
docs_dir: docs/
repo_name: "vipul43/project-blip"
repo_url: "https://github.com/vipul43/project-blip"
nav:
  - API: API.md
  - Database: DB.md
  - Deployment: DEPLOY.md
  - Development: DEVELOP.md
theme:
  name: "material"
